# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d91e042ca2678c25758fd685d3ccf8b478408eb394560d5cbc6b5296cfa5c5be4e2134d99f4466ee045b4536ba4cc8dac66f122a94f52958e01f2759a73fa2d4

test:
  secret_key_base: bef4bf564c1b9c8810ee10e0acd23121c3966c4ef8b70628c15da4aaf3e3871d36f1035e7097b9749c86eabcac026da6ab2ed304e0b167df61ea34cd3dc195f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
